---
name: opensearch
pack: sample_pack
description: Trigger OpenSearch pipeline
enabled: true

trigger:
  type: core.st2.webhook
  parameters:
    url: sample

action:
  ref: sample_pack.echo_action
  parameters:
    message: "{{ trigger.body.message }}"
    another_message: "{{ trigger.body.message }}"